Food/Controllers/System/ProductDetailController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Food.Data;
using Food.Entity;
using Food.Models;
using Food.StatisFile.Function;

namespace Food.Controllers
{
    public class ProductDetailController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly SignInManager<AppUser> _SignInManager;
        private readonly UserManager<AppUser> _UserManager;

        public ProductDetailController(ApplicationDbContext context, UserManager<AppUser> UserManager, SignInManager<AppUser> SignInManager)
        {
            _context = context;
            _UserManager = UserManager;
            _SignInManager = SignInManager;
        }




        [Route("/productdetail")]
        [HttpGet("{id}")]
        public IActionResult Index(string id)
        {
            //Count product in cart page
            string namePc = Environment.MachineName;
            bool checkLogin = (User?.Identity.IsAuthenticated).GetValueOrDefault();
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userIdString = "";
            if (userId != null)
            {
                userIdString = userId.ToString();
            }
            ViewBag.CountProductInCart = CheckCart.CheckProudctCart(_context, namePc, checkLogin, userIdString);
            //Mess
            ViewBag.Mess = "";
            //Query product

            var productDetailQuery = _context.Products.FirstOrDefault(a => a.pd_Id == id);


            ViewBag.Id = productDetailQuery.pd_Id;
            ViewBag.Img1 = productDetailQuery.pd_Img1;
            ViewBag.Img2 = productDetailQuery.pd_Img2;
            ViewBag.Img3 = productDetailQuery.pd_Img3;
            ViewBag.Img4 = productDetailQuery.pd_Img4;
            ViewBag.NameProduct = productDetailQuery.pd_Name;
            ViewBag.Price = productDetailQuery.pd_Price;
            ViewBag.Rate = productDetailQuery.pd_Rate;
            ViewBag.ShortDescription = productDetailQuery.pd_ShortDescription;
            ViewBag.Description = productDetailQuery.pd_Description;



            var review = from a in _context.AppUser
                         join b in _context.Reviews on a.Id equals b.review_UserId
                         join c in _context.ReviewInproduct on b.review_id equals c.rip_ReviewId
                         join d in _context.Products on c.rip_ProductId equals d.pd_Id
                         select new { a, b, c, d };



            review = review.Where(x => x.d.pd_Id == id && x.b.review_HideStatus == false).OrderBy(x => x.b.review_UploadTime); ;

            var reviewQuery = review.Select(x => new ReviewModel()
            {
                // table Review
                review_id = x.b.review_id,
                review_UserId = x.a.Id,
                review_ProductId = x.d.pd_Id,
                review_Comment = x.b.review_Comment,
                review_UserName = x.a.UserName,
                review_UploadTime = x.b.review_UploadTime,

                review_CountSubReview = 1
                //// table SubReview
                //Subreview = 

                
            });



            var queryProduct = _context.Products;

            ViewBag.ProductList = queryProduct;




            return View(reviewQuery);
        }

        [Route("/AddToCart")]
        [HttpPost]
        public async Task<IActionResult> AddToCart()
        {

            try
            {
                
                string namePc = Environment.MachineName;
                bool checkLogin = (User?.Identity.IsAuthenticated).GetValueOrDefault();
                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var userName = User.FindFirstValue(ClaimTypes.Name);

                var productid = Request.Form["productid"];
                var quantity = Request.Form["quantityProuct"];

                int quantityProduct = Int16.Parse(quantity);
                string cartId = Guid.NewGuid().ToString();

                

                if (checkLogin)
                {
                    // Logined
                    // Query cart
                    var queryCart = _context.Cart.FirstOrDefault(a => a.cart_UserID == userId.ToString());

                    if (queryCart == null)
                    {
                        //Create cart 
                        var cartCreate = new Cart()
                        {
                            cart_Id = cartId,
                            cart_UserID = userId
                        };
                        _context.Cart.Add(cartCreate);
                    }
                    else
                    {
                        cartId = queryCart.cart_Id;
                    }
                    
                     //Create ProductInCart
                    var ProductInCartCreate = new ProductInCart()
                    {
                        pic_CartId = cartId,
                        pic_ProductId = productid.ToString(),
                        pic_amount = quantityProduct,
                    };
                    _context.ProductInCart.Add(ProductInCartCreate);


                    await _context.SaveChangesAsync();
                }else
                {
                    /// No logined
                    /// Create Device in DB
                    var deviceQuery = _context.Devices.FirstOrDefault(a => a.deviceName == namePc);

                    if (deviceQuery == null)
                    {
                        string DeviceId = Guid.NewGuid().ToString();
                        var AddDevice = new Device()
                        {
                            deviceId = DeviceId,
                            deviceName = namePc
                        };
                        _context.Devices.Add(AddDevice);
                        await _context.SaveChangesAsync();
                    }
                    /// Create Device in DB
                    var deviceQueryre = _context.Devices.FirstOrDefault(a => a.deviceName == namePc);

                    //Create cart
                    var CartsDevice = new CartsDevice()
                    {
                        cartd_Id = cartId,
                        cartd_DeviceId = deviceQueryre.deviceId
                    };

                    _context.CartsDevice.Add(CartsDevice);
                    var ProductInCartDevices = new ProductInCartDevices()
                    {
                        picd_CartId = cartId,
                        picd_ProductId = productid.ToString(),
                        picd_amount = quantityProduct
                    };

                    _context.ProductInCartDevices.Add(ProductInCartDevices);
                    await _context.SaveChangesAsync();
                }
                return Redirect("/cart");
            }
            catch
            {
                return View();
            }

        }

        [Route("/productcomment")]
        [HttpPost]
        public async Task<IActionResult> Comment()
        {
            try
            {
                ViewBag.Mess = "";
                string idproduct = Request.Form["idproduct"];
                bool checkLogin = (User?.Identity.IsAuthenticated).GetValueOrDefault();
                if(checkLogin)
                {
                    var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    var userName = User.FindFirstValue(ClaimTypes.Name);
                    string reviewId = Guid.NewGuid().ToString();

                    
                    if (Request.Form["comment"] != "")
                    {
                        var reviews = new Reviews()
                        {
                            review_id = reviewId,
                            review_Comment = Request.Form["comment"],
                            review_UserId = userId,
                            review_UploadTime = DateTime.Now,
                            review_HideStatus = false,
                            review_ReviewType = "Review"
                        };

                        _context.Reviews.Add(reviews);
                        var reviewInProduct = new ReviewInproduct()
                        {
                            rip_ProductId = idproduct,
                            rip_ReviewId = reviewId
                        };
                        _context.ReviewInproduct.Add(reviewInProduct);
                        await _context.SaveChangesAsync();
                    }
                }
                else
                {
                    ViewBag.Mess = "Need to login"; 
                }
                return Redirect("/productdetail?id=" + idproduct);
            }
            catch
            {
                ViewBag.thongbao = "Cann't create";
                return View();
            }

        }

        [Route("/productcommentreply")]
        [HttpPost]
        public async Task<IActionResult> Commentreply()
        {

            try
            {

                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var userName = User.FindFirstValue(ClaimTypes.Name);
                string SubReviewId = Guid.NewGuid().ToString();

                string idproduct = Request.Form["idproduct"];
                if (Request.Form["subcomment"] != "")
                {
                    var SubReviews = new SubReview()
                    {
                        subReview_Id = SubReviewId,
                        subReview_Commnet = Request.Form["subcomment"],
                        subReview_DateCommnet = DateTime.Now,
                        subReview_UserId = userId,
                        subReview_HideStatus = false,
                        subreview_SubReviewType = "SubReview"
                    };

Food/Views/ProductDetail/Index.cshtml
@model IEnumerable<Food.Models.ReviewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<!-- catg header banner section -->
<section id="aa-catg-head-banner">
    <img src="/images/banner/foodservice-mfg-hero-1920x300.jpg" alt="fashion img">
    <div class="aa-catg-head-banner-area">
        <div class="container">
            <div class="aa-catg-head-banner-content">
                <h2>@ViewBag.NameProduct</h2>
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="#">Product</a></li>
                    <li class="active">@ViewBag.NameProduct</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!-- / catg header banner section -->
<!-- product category -->
<section id="aa-product-details">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="aa-product-details-area">
                    <div class="aa-product-details-content">
                        <div class="row">
                            <!-- Modal view slider -->
                            <div class="col-md-5 col-sm-5 col-xs-12">
                                <div class="aa-product-view-slider">
                                    <div id="demo-1" class="simpleLens-gallery-container">
                                        <div class="simpleLens-container">
                                            <div class="simpleLens-big-image-container"><a data-lens-image="@ViewBag.Img1" class="simpleLens-lens-image"><img src="@ViewBag.Img1" class="simpleLens-big-image"></a></div>
                                        </div>
                                        <div class="simpleLens-thumbnails-container">
                                            <a data-big-image="@ViewBag.Img1" data-lens-image="@ViewBag.Img1" class="simpleLens-thumbnail-wrapper" href="#">
                                                <img src="@ViewBag.Img1" height="80" width="40">
                                            </a>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Modal view content -->
                            <div class="col-md-7 col-sm-7 col-xs-12">
                                <div class="aa-product-view-content">
                                    <h3>@ViewBag.NameProduct</h3>
                                    <div class="aa-price-block">
                                        <span class="aa-product-view-price">$@ViewBag.Price</span>

                                    </div>
                                    <p>@ViewBag.ShortDescription</p>

                                    <form asp-controller="ProductDetail" asp-action="AddToCart" method="post">
                                        <div class="aa-prod-quantity">
                                            <select id="quantityProuct" name="quantityProuct">
                                                <option selected="1" value="1">1</option>
                                                <option value="2">2</option>
                                                <option value="3">3</option>
                                                <option value="4">4</option>
                                                <option value="5">5</option>
                                                <option value="6">6</option>
                                            </select>
                                        </div>
                                        <div>
                                            <input type="text" name="productid" value="@ViewBag.Id" id="productid" hidden />
                                        </div>
                                        <div class="aa-prod-view-bottom">
                                            <input type="submit" class="aa-add-to-cart-btn" value="Add To Cart" />
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="aa-product-details-bottom">
                        <ul class="nav nav-tabs" id="myTab2">
                            <li><a href="#description" data-toggle="tab">Description</a></li>
                            <li><a href="#review" data-toggle="tab">Reviews</a></li>
                        </ul>

                        <!-- Tab panes comment-->
                        <div class="tab-content">
                            <div class="tab-pane fade in active" id="description">
                                <p>@ViewBag.Description</p>
                            </div>
                            <div class="tab-pane fade " id="review">
                                <div class="aa-product-review-area">
                                    <h4>2 Reviews for Food</h4>
                                    <ul class="aa-review-nav">

                                        @{
                                            foreach (var item in Model)
                                            {
                                                <li>
                                                    <div class="media">
                                                        <div class="media-left">
                                                            <a href="#">
                                                                <img class="media-object" src="images/Users/userBlack-150-150.png" alt="girl image">
                                                            </a>
                                                        </div>
                                                        <div class="media-body">
                                                            <h4 class="media-heading"><strong>@item.review_UserName</strong> - <span>@item.review_UploadTime</span></h4>
                                                            <p>@item.review_Comment</p>
                                                        </div>
                                                    </div>
                                                </li>
                                            }
                                        }

                                    </ul>
                                    <h4>Add a Comment</h4>

                                    <!-- review form -->
                                    <div class="container">
                                        <form asp-controller="ProductDetail" asp-action="Comment" method="post">
                                            <div class="form-group row">
                                                <input type="text" id="" name="idproduct" value="@ViewBag.Id" hidden />
                                            </div>
                                            <div class="form-group row">
                                                <input type="text" id="" name="comment" />
                                            </div>
                                            <div class="form-group">
                                                <input type="submit" value="Comment" />
                                            </div>
                                        </form>
                                        <label>@ViewBag.Mess</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- Related product -->
                    <div class="aa-product-related-item">
                        <h3>Related Products</h3>
                        <ul class="aa-product-catg aa-related-item-slider">
                            @{
                                foreach (var item in ViewBag.ProductList)
                                {
                                    <!-- start single product item -->
                                    <li>
                                        <figure>
                                            <a class="aa-product-img" href="/productdetail?id=@item.pd_Id"><img src="@item.pd_Img1" alt="polo shirt img"></a>
                                            <a class="aa-add-card-btn" href="/productdetail?id=@item.pd_Id"><span class="fa fa-shopping-cart"></span>Add To Cart</a>
                                            <figcaption>
                                                <h4 class="aa-product-title"><a href="/productdetail?id=@item.pd_Id">@item.pd_Name</a></h4>
                                                <span class="aa-product-price">$@item.pd_Price</span>
                                            </figcaption>
                                        </figure>
                                    </li>
                                }
                            }







                        </ul>
                        <!-- quick view modal -->
                        
                        <!-- / quick view modal -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- / product category -->




<script src="https://www.google.com/recaptcha/api.js" async defer></script>